version: "3"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app

  web:
    build: web
    tty: true
    depends_on:
      - db
    environment:
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - ./web:/web
    networks:
      - app

networks:
  app:
    driver: bridge
